[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "form-action https:"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=2592000"
    Feature-Policy = '''
    ambient-light-sensor 'none';
    vibrate 'none';
    geolocation 'none';
    midi 'none';
    microphone 'none';
    camera 'none';
    magnetometer 'none';
    speaker 'none'
    unoptimised-images 'none'
    '''
